/*
 * Wallet API Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.WalletResult2Membership;
import javax.validation.constraints.*;

/**
 * MembershipResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-07-18T17:40:34.896Z")
public class MembershipResult   {
  @JsonProperty("membership")
  private WalletResult2Membership membership = null;

  public MembershipResult membership(WalletResult2Membership membership) {
    this.membership = membership;
    return this;
  }

  /**
   * Get membership
   * @return membership
   **/
  @JsonProperty("membership")
  @ApiModelProperty(value = "")
  public WalletResult2Membership getMembership() {
    return membership;
  }

  public void setMembership(WalletResult2Membership membership) {
    this.membership = membership;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MembershipResult membershipResult = (MembershipResult) o;
    return Objects.equals(this.membership, membershipResult.membership);
  }

  @Override
  public int hashCode() {
    return Objects.hash(membership);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MembershipResult {\n");
    
    sb.append("    membership: ").append(toIndentedString(membership)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

