/*
 * Wallet API Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * Wallet
 */
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-07-18T17:40:34.896Z")
public class Wallet   {
  @JsonProperty("walletId")
  private String walletId = null;

  @JsonProperty("cardType")
  private String cardType = null;

  @JsonProperty("payType")
  private String payType = null;

  @JsonProperty("cardHolderName")
  private String cardHolderName = null;

  @JsonProperty("cardNumber")
  private String cardNumber = null;

  @JsonProperty("firstTwoDigits") 
  private String firstTwoDigits = null;

  @JsonProperty("lastFourDigits")
  private String lastFourDigits = null;

  @JsonProperty("expiryDate")
  private String expiryDate = null;

  @JsonProperty("status")
  private String status = null;

  public Wallet walletId(String walletId) {
    this.walletId = walletId;
    return this;
  }

  /**
   * The unique wallet id
   * @return walletId
   **/
  @JsonProperty("walletId")
  @ApiModelProperty(example = "walleT_12345678", required = true, value = "The unique wallet id")
  @NotNull
  public String getWalletId() {
    return walletId;
  }

  public void setWalletId(String walletId) {
    this.walletId = walletId;
  }

  public Wallet cardType(String cardType) {
    this.cardType = cardType;
    return this;
  }

  /**
   * Card Type
   * @return cardType
   **/
  @JsonProperty("cardType")
  @ApiModelProperty(example = "VI", required = true, value = "Card Type")
  @NotNull
  public String getCardType() {
    return cardType;
  }

  public void setCardType(String cardType) {
    this.cardType = cardType;
  }

  public Wallet payType(String payType) {
    this.payType = payType;
    return this;
  }

  /**
   * Card Type
   * @return payType
   **/
  @JsonProperty("payType")
  @ApiModelProperty(example = "CP", required = true, value = "Card Type")
  @NotNull
  public String getPayType() {
    return payType;
  }

  public void setPayType(String payType) {
    this.payType = payType;
  }

  public Wallet cardHolderName(String cardHolderName) {
    this.cardHolderName = cardHolderName;
    return this;
  }

  /**
   * Card Holder name
   * @return cardHolderName
   **/
  @JsonProperty("cardHolderName")
  @ApiModelProperty(example = "first_name last_name", required = true, value = "Card Holder name")
  @NotNull
  public String getCardHolderName() {
    return cardHolderName;
  }

  public void setCardHolderName(String cardHolderName) {
    this.cardHolderName = cardHolderName;
  }

  public Wallet cardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
    return this;
  }

  /**
   * credit card number
   * @return cardNumber
   **/
  @JsonProperty("cardNumber")
  @ApiModelProperty(example = "1234567890", required = true, value = "credit card number")
  @NotNull
  public String getCardNumber() {
    return cardNumber;
  }

  public void setCardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
  }

  public Wallet firstTwoDigits(String firstTwoDigits) {
    this.firstTwoDigits = firstTwoDigits;
    return this;
  }

  /**
   * first two digits of credit card number
   * @return firstTwoDigits
   **/
  @JsonProperty("firstTwoDigits")
  @ApiModelProperty(example = "12", value = "first two digits of credit card number")
  public String getFirstTwoDigits() {
    return firstTwoDigits;
  }

  public void setFirstTwoDigits(String firstTwoDigits) {
    this.firstTwoDigits = firstTwoDigits;
  }

  public Wallet lastFourDigits(String lastFourDigits) {
    this.lastFourDigits = lastFourDigits;
    return this;
  }

  /**
   * last four digits of credit card number
   * @return lastFourDigits
   **/
  @JsonProperty("lastFourDigits")
  @ApiModelProperty(example = "7890", value = "last four digits of credit card number")
  public String getLastFourDigits() {
    return lastFourDigits;
  }

  public void setLastFourDigits(String lastFourDigits) {
    this.lastFourDigits = lastFourDigits;
  }

  public Wallet expiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

  /**
   * expiry date of card
   * @return expiryDate
   **/
  @JsonProperty("expiryDate")
  @ApiModelProperty(example = "01/25", required = true, value = "expiry date of card")
  @NotNull
  public String getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
  }

  public Wallet status(String status) {
    this.status = status;
    return this;
  }

  /**
   * Card status in Wallet. 0 - Active, 1 - inactive, 2 - prefered
   * @return status
   **/
  @JsonProperty("status")
  @ApiModelProperty(example = "0", value = "Card status in Wallet. 0 - Active, 1 - inactive, 2 - prefered")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Wallet wallet = (Wallet) o;
    return Objects.equals(this.walletId, wallet.walletId) &&
        Objects.equals(this.cardType, wallet.cardType) &&
        Objects.equals(this.payType, wallet.payType) &&
        Objects.equals(this.cardHolderName, wallet.cardHolderName) &&
        Objects.equals(this.cardNumber, wallet.cardNumber) &&
        Objects.equals(this.firstTwoDigits, wallet.firstTwoDigits) &&
        Objects.equals(this.lastFourDigits, wallet.lastFourDigits) &&
        Objects.equals(this.expiryDate, wallet.expiryDate) &&
        Objects.equals(this.status, wallet.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(walletId, cardType, payType, cardHolderName, cardNumber, firstTwoDigits, lastFourDigits, expiryDate, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Wallet {\n");
    
    sb.append("    walletId: ").append(toIndentedString(walletId)).append("\n");
    sb.append("    cardType: ").append(toIndentedString(cardType)).append("\n");
    sb.append("    payType: ").append(toIndentedString(payType)).append("\n");
    sb.append("    cardHolderName: ").append(toIndentedString(cardHolderName)).append("\n");
    sb.append("    cardNumber: ").append(toIndentedString(cardNumber)).append("\n");
    sb.append("    firstTwoDigits: ").append(toIndentedString(firstTwoDigits)).append("\n");
    sb.append("    lastFourDigits: ").append(toIndentedString(lastFourDigits)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

